# Generated by Django 2.0.7 on 2018-07-23 01:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.BooleanField(default=False)),
                ('african_traje', models.BooleanField(default=False)),
                ('main_image', models.ImageField(blank=True, default=' ', max_length=45, upload_to='uploads/clothing/')),
                ('Popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoClothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=45, upload_to='uploads/clothing/')),
                ('clothing_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woman.Clothing')),
            ],
        ),
    ]
