# Generated by Django 2.0.7 on 2018-07-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='main_image',
            field=models.ImageField(default=' ', max_length=45, upload_to='uploads/clothing/'),
        ),
    ]
