# Generated by Django 2.0.7 on 2018-07-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woman', '0002_auto_20180723_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='main_image',
            new_name='artwork',
        ),
    ]
