# Generated by Django 2.0.7 on 2018-07-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woman', '0003_auto_20180723_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
